### PR TITLE
Resolve PORTER_HOME when it's symlinked

### PR DESCRIPTION
**Pull request by carolynvs**
When someone symlinks /usr/local/bin/porter from ~/.porter/porter, we need to handle that properly
so that we can still find the mixins and other assets in the original directory.

Also cache the resolved PORTER_HOME so we don't have to do that more than once.

### CODE REVIEW

**Comment by radu-matei** [comment]
There are a bunch of other tests failing on Windows, but one introduced by this PR:

```
--- FAIL: TestConfig_GetHomeDirFromSymlink (0.17s)
    logger.go:11: Resolved porter binary from /usr/local/bin/porter to /root/.porter/porter

    config_test.go:38:
                Error Trace:    config_test.go:38
                Error:          Not equal:
                                expected: "/root/.porter"
                                actual  : "\\root\\.porter"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/root/.porter
                                +\root\.porter
                Test:           TestConfig_GetHomeDirFromSymlink
```

**Comment by carolynvs** [comment]
@radu-matei Thank you for trying this out on Windows! If you know how to setup an agent on Azure Devops for Windows, we'd appreciate help getting that setup, or a pointer to how you did it for duffle (or some other project).

Fixing now.

**Comment by carolynvs** [comment]
Fixing now = setting up a windows dev VM so gimme a few hours 😀

**Comment by carolynvs** [comment]
OK got a different makefile setup to catch these problems. I'll fix this test that I broke and then fix the test and add the new CI setup in another PR so we don't break it again. 😊

**Pull request merged**
