### PR TITLE
Made credentials required by default by adding UnmarshalYAML method to CredentialDefinition type

### PR DESCRIPTION
**Pull request by AGMETEOR**
# What does this change
This PR adds a method, `UnmarshalYAML` to the CredentialDefinition struct to always mark a credential's definition as required i.e. `true` when unmarshaling from a YAML to create a manifest file. This makes credentials required by default.

# What issue does it fix
[#577](https://github.com/deislabs/porter/issues/577)

[1]: https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
- In the spec for this issue, it's mentioned that `THERE IS NO WARNING. The bundle just fails in odd places with unexpected errors because the bundle was written assuming credentials would be there, and they aren't.` Can this be solved within this issue?
- Also, I was not sure on how to exactly test the change made and what I did was to create a YAML file `with-credentials.yaml` with some credentials defined. Some advice here would be appreciated.

# Checklist
- [x] Unit Tests
- [x] Documentation
  - [ ] Documentation Not Impacted

### CODE REVIEW

**Comment by carolynvs** [comment]
@AGMETEOR Is your pull request ready for someone to review? If so, please click the "Ready for review button" at the bottom of your pull request.

Screen Shot 2019-09-30 at 9 23 47 AM

**Comment by carolynvs** [comment]
> In the spec for this issue, it's mentioned that THERE IS NO WARNING. The bundle just fails in odd places with unexpected errors because the bundle was written assuming credentials would be there, and they aren't. Can this be solved within this issue?

This is why we decided that in Porter, credentials are required by default. It will avoid that usability problem. 😀 

There is a larger discussion coming up in the spec around being able to specify that a credential only applies to a specific action, https://github.com/deislabs/cnab-spec/issues/279. That is a while off though because it would require a spec version bump.

So for now this PR you just submitted is our workaround. 👍

**Comment by vdice** [comment]
Integration tests look good.  The `cli_test` failure is separate from this PR (exists on master).  I've issued a proposed fix in https://github.com/deislabs/porter/pull/671.

Thank you for this feature @AGMETEOR !  Have been looking forward to this update for some time :)

**Pull request merged**
